export const fronEndSkills =[
    {
      id:1,
      skill:"HTML",
      level:"Experienced"
    },
    {
      id:2,
      skill:"CSS",
      level:"Experienced"
    },
    {
      id:3,
      skill:"Bootstrap",
      level:"Intermediate"
    },
    {
      id:4,
      skill:"TypeScript",
      level:"Intermediate"
    },
    {
      id:5,
      skill:"JavaScript",
      level:"Experienced"
    },
    {
      id:6,
      skill:"React",
      level:"Experienced"
    },
  ];
  export const backEndSkills =[
    {
      id:1,
      skill:"NodeJS",
      level:"Experienced"
    },
    {
      id:2,
      skill:"Express",
      level:"Experienced"
    },
    {
      id:3,
      skill:"MongoDB",
      level:"Intermediate"
    },
    {
      id:4,
      skill:"Mongoose",
      level:"Intermediate"
    },
    {
      id:5,
      skill:"Microsoft SSMS",
      level:"beginner"
    },
    {
      id:6,
      skill:"Java",
      level:"Beginner"
    },
  ];